#!/usr/bin/env python3
"""Test compliance of emails actually generated by system templates"""

import requests
import json
from database import get_db, init_db
from intelligence.activation_interventions import (
    generate_dead_on_arrival_email,
    generate_stuck_in_sandbox_email,
    generate_production_blocked_email
)

init_db()

# Get a valid partner to test
partner_id = 28  # Abound
with get_db() as conn:
    # Verify partner exists
    result = conn.execute(
        """SELECT p.name FROM partners_activated pa
           JOIN prospects p ON pa.prospect_id = p.id
           WHERE pa.prospect_id = ?""",
        (partner_id,)
    ).fetchone()

stall_data = {
    'days_of_inactivity': 14,
    'api_calls_made': 0,
    'error_codes': [],
    'last_error_code': 'AUTH_FAILED',
    'recent_errors': [{'code': 'AUTH_FAILED', 'message': 'Invalid API key'}],
    'likely_cause': 'Integration never started',
    'severity': 'high'
}

BASE_URL = "http://localhost:8000/api"

print("="*80)
print("TESTING COMPLIANCE OF SYSTEM-GENERATED EMAILS")
print("="*80)

# Test 1: DEAD_ON_ARRIVAL
print("\n1. DEAD_ON_ARRIVAL Template Email:")
print("-" * 60)
email1 = generate_dead_on_arrival_email(partner_id)
response = requests.post(
    f"{BASE_URL}/activate/email/check-compliance",
    json={
        "subject": email1['subject'],
        "body": email1['body'],
        "recipient_name": "Engineering Lead",
        "recipient_email": "eng@company.com"
    }
)
if response.status_code == 200:
    result = response.json()
    score = result.get('compliance_score', 0)
    print(f"Subject: {email1['subject'][:60]}...")
    print(f"Body length: {len(email1['body'])} chars")
    print(f"Compliance Score: {score}/100")
    print(f"Status: {'✓ COMPLIANT' if result.get('is_compliant') else '✗ NOT COMPLIANT'}")
    if result.get('warnings'):
        print(f"Warnings ({len(result['warnings'])}):")
        for w in result['warnings'][:5]:
            print(f"  - {w['type']}: {w['message'][:70]}...")
else:
    print(f"✗ Error: {response.status_code}")

# Test 2: STUCK_IN_SANDBOX
print("\n2. STUCK_IN_SANDBOX Template Email:")
print("-" * 60)
email2 = generate_stuck_in_sandbox_email(partner_id, stall_data)
response = requests.post(
    f"{BASE_URL}/activate/email/check-compliance",
    json={
        "subject": email2['subject'],
        "body": email2['body'],
        "recipient_name": "Engineering Team",
        "recipient_email": "eng@company.com"
    }
)
if response.status_code == 200:
    result = response.json()
    score = result.get('compliance_score', 0)
    print(f"Subject: {email2['subject'][:60]}...")
    print(f"Body length: {len(email2['body'])} chars")
    print(f"Compliance Score: {score}/100")
    print(f"Status: {'✓ COMPLIANT' if result.get('is_compliant') else '✗ NOT COMPLIANT'}")
    if result.get('warnings'):
        print(f"Warnings ({len(result['warnings'])}):")
        for w in result['warnings'][:5]:
            print(f"  - {w['type']}: {w['message'][:70]}...")
else:
    print(f"✗ Error: {response.status_code}")

# Test 3: PRODUCTION_BLOCKED
print("\n3. PRODUCTION_BLOCKED Template Email:")
print("-" * 60)
email3 = generate_production_blocked_email(partner_id, stall_data)
response = requests.post(
    f"{BASE_URL}/activate/email/check-compliance",
    json={
        "subject": email3['subject'],
        "body": email3['body'],
        "recipient_name": "Leadership Team",
        "recipient_email": "ceo@company.com"
    }
)
if response.status_code == 200:
    result = response.json()
    score = result.get('compliance_score', 0)
    print(f"Subject: {email3['subject'][:60]}...")
    print(f"Body length: {len(email3['body'])} chars")
    print(f"Compliance Score: {score}/100")
    print(f"Status: {'✓ COMPLIANT' if result.get('is_compliant') else '✗ NOT COMPLIANT'}")
    if result.get('warnings'):
        print(f"Warnings ({len(result['warnings'])}):")
        for w in result['warnings'][:5]:
            print(f"  - {w['type']}: {w['message'][:70]}...")
else:
    print(f"✗ Error: {response.status_code}")

print("\n" + "="*80)
print("SUMMARY: Are system-generated emails 100/100 compliant?")
print("="*80)
